export const spotifyCategories: { [category: string]: boolean } = {
    "new-release": false,
    "pop": false,
    "synth-pop": false,
    "hip-Hop": false,
    "dance/Electronic": false,
    "indie": false,
    "rock": false,
    "fresh-finds": false,
    "discover": false,
    "country": false,
    "chill": false,
    "r-n-b": false,
    "metal": false,
    "decades": false,
    "latin": false,
    "k-pop": false,
    "party": false,
    "love": false,
    "jazz": false,
    "summer": false,
    "trending": false,
    "classical": false,
    "folk & Acoustic": false,
    "soul": false,
    "anime": false,
    "gaming": false,
    "movies": false,
    "instrumental": false,
    "punk": false,
    "blues": false,
    "alternative": false,
  };