export const spotifyCategories: { [category: string]: boolean } = {
    "made For You": false,
    "new Releases": false,
    "pop": false,
    "hip-Hop": false,
    "dance/Electronic": false,
    "indie": false,
    "charts": false,
    "in the car": false,
    "rock": false,
    "mood": false,
    "fresh Finds": false,
    "discover": false,
    "country": false,
    "chill": false,
    "r&B": false,
    "metal": false,
    "decades": false,
    "reggae": false,
    "afro": false,
    "latin": false,
    "k-pop": false,
    "sleep": false,
    "party": false,
    "love": false,
    "dansband": false,
    "jazz": false,
    "summer": false,
    "trending": false,
    "classical": false,
    "folk & Acoustic": false,
    "soul": false,
    "anime": false,
    "workout": false,
    "gaming": false,
    "netflix": false,
    "tv & movies": false,
    "instrumental": false,
    "punk": false,
    "ambient": false,
    "blues": false,
    "alternative": false,
  };